Document: install-debian
Title: Debian install-debian Manual
Author: <insert document author here>
Abstract: This manual describes what install-debian is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/install-debian/install-debian.sgml.gz

Format: postscript
Files: /usr/share/doc/install-debian/install-debian.ps.gz

Format: text
Files: /usr/share/doc/install-debian/install-debian.text.gz

Format: HTML
Index: /usr/share/doc/install-debian/html/index.html
Files: /usr/share/doc/install-debian/html/*.html
